### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Eyesrare** [ArkTechMC/AnnoyingVillagers#1]
whenever i enter third person mode, i crash.
heres the log:

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2024-11-03 21:54:51
Description: Rendering entity in world

java.lang.NoClassDefFoundError: dev/emi/trinkets/api/TrinketsApi
	at knot//com.iafenvoy.neptune.render.tool.fabric.BackBeltToolManagerImpl.getAllEquipped(BackBeltToolManagerImpl.java:22)
	at knot//com.iafenvoy.neptune.render.tool.BackBeltToolManager.getAllEquipped(BackBeltToolManager.java)
	at knot//com.iafenvoy.neptune.render.tool.BackToolRenderer.render(BackToolRenderer.java:33)
	at knot//com.iafenvoy.neptune.render.tool.BackToolRenderer.method_4199(BackToolRenderer.java:22)
	at knot//net.minecraft.class_922.method_4054(class_922.java:145)
	at knot//net.minecraft.class_1007.method_4215(class_1007.java:66)
	at knot//net.minecraft.class_1007.method_3936(class_1007.java:43)
	at knot//net.minecraft.class_898.method_3954(class_898.java:145)
	at knot//net.minecraft.class_761.method_22977(class_761.java:1574)
	at knot//net.minecraft.class_761.method_22710(class_761.java:1324)
	at knot//net.minecraft.class_757.method_3188(class_757.java:1110)
	at knot//net.minecraft.class_757.method_3192(class_757.java:880)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1219)
	at knot//net.minecraft.class_310.method_1514(class_310.java:802)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: dev.emi.trinkets.api.TrinketsApi
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 18 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//com.iafenvoy.neptune.render.tool.fabric.BackBeltToolManagerImpl.getAllEquipped(BackBeltToolManagerImpl.java:22)
	at knot//com.iafenvoy.neptune.render.tool.BackBeltToolManager.getAllEquipped(BackBeltToolManager.java)
	at knot//com.iafenvoy.neptune.render.tool.BackToolRenderer.render(BackToolRenderer.java:33)
	at knot//com.iafenvoy.neptune.render.tool.BackToolRenderer.method_4199(BackToolRenderer.java:22)
	at knot//net.minecraft.class_922.method_4054(class_922.java:145)
	at knot//net.minecraft.class_1007.method_4215(class_1007.java:66)
	at knot//net.minecraft.class_1007.method_3936(class_1007.java:43)
	at knot//net.minecraft.class_898.method_3954(class_898.java:145)
	at knot//net.minecraft.class_761.method_22977(class_761.java:1574)
	at knot//net.minecraft.class_761.method_22710(class_761.java:1324)
	at knot//net.minecraft.class_757.method_3188(class_757.java:1110)

-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 210
	Entity Name: {MINECRAFT_USERNAME}
	Entity's Exact location: 67.48, 78.00, -1.55
	Entity's Block location: World: (67,78,-2), Section: (at 3,14,14 in 4,4,-1; chunk contains blocks 64,-64,-16 to 79,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at knot//net.minecraft.class_898.method_3954(class_898.java:145)
	at knot//net.minecraft.class_761.method_22977(class_761.java:1574)
	at knot//net.minecraft.class_761.method_22710(class_761.java:1324)
	at knot//net.minecraft.class_757.method_3188(class_757.java:1110)
	at knot//net.minecraft.class_757.method_3192(class_757.java:880)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1219)
	at knot//net.minecraft.class_310.method_1514(class_310.java:802)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_1007@7e2a9fc1
	Location: -0.04,-1.83,3.99 - World: (-1,-2,3), Section: (at 15,14,3 in -1,-1,0; chunk contains blocks -16,-64,0 to -1,319,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Rotation: 0.6000001
	Delta: 0.17999959
Stacktrace:
	at knot//net.minecraft.class_898.method_3954(class_898.java:145)
	at knot//net.minecraft.class_761.method_22977(class_761.java:1574)
	at knot//net.minecraft.class_761.method_22710(class_761.java:1324)
	at knot//net.minecraft.class_757.method_3188(class_757.java:1110)
	at knot//net.minecraft.class_757.method_3192(class_757.java:880)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1219)
	at knot//net.minecraft.class_310.method_1514(class_310.java:802)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['{MINECRAFT_USERNAME}'/210, l='ClientLevel', x=67.48, y=78.00, z=-1.55]]
	Chunk stats: 1024, 486
	Level dimension: minecraft:overworld
	Level spawn location: World: (64,78,0), Section: (at 0,14,0 in 4,4,0; chunk contains blocks 64,-64,0 to 79,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 60 game time, 60 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at knot//net.minecraft.class_638.method_8538(class_638.java:458)
	at knot//net.minecraft.class_310.method_1587(class_310.java:2406)
	at knot//net.minecraft.class_310.method_1514(class_310.java:821)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.13, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 300757472 bytes (286 MiB) / 1362100224 bytes (1299 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 4500 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 96 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f0a
	Graphics card #0 versionInfo: DriverVersion=31.0.15.5152
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 22657.69
	Virtual memory used (MB): 19450.36
	Swap memory total (MB): 6400.00
	Swap memory used (MB): 160.77
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M
	Fabric Mods: 
		annoying_villagers: Annoying Villagers 0.2
		architectury: Architectury 9.2.14
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		iris: Iris 1.7.5+mc1.20.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.1
		neptune: Neptune 1.4.3
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.4+1.20.1
				porting_lib_core: Porting Lib Core 2.3.4+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.4+1.20.1
			sponsor_core: Sponsor Core 1.0.0
		sodium: Sodium 0.5.11+mc1.20.1
	Loaded Shaderpack: (off)
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 3.2.0 NVIDIA 551.52, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: en_us
	CPU: 12x AMD Ryzen 5 4500 6-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['{MINECRAFT_USERNAME}'/210, l='ServerLevel[New World]', x=67.48, y=78.00, z=-1.55]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

**Comment by IAFEnvoy** [comment]
Install trinkets. It is one of the dependencies.

**Comment by Eyesrare** [comment]
thank you so much, that worked
